POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Əli və Nino",
  "isbn": "978-3-16",
  "publicationYear": 1937,
  "authorId": 1
}

###
POST http://localhost:8080/api/authors
Content-Type: application/json

{
"name": "Cəlil Məmmədquluzadə",
"nationality": "Azərbaycan"
}

###

PUT http://localhost:8080/api/books/1
Content-Type: application/json

{
  "title": "Əli və Nino (Yenilənmiş)",
  "isbn": "978-3-16",
  "publicationYear": 1937,
  "authorId": 1
}

###
GET http://localhost:8080/api/books?page=0&size=2&sort=title,asc

###

GET http://localhost:8080/api/books/999

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "saiq",
  "password": "test1234"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "saiq",
  "password": "test1234"
}

###

GET http://localhost:8080/api/books
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzYWlxIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODU1OTAzNzgsImV4cCI6MTc4NTY3Njc3OH0.ZlacnFec1kPsm3Hd_PVksb0Q-_SWNxxLZXp_4GDIkDpMR2RLNHcZv4lGuo6rxQuT

###

DELETE http://localhost:8080/api/books/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJzYWlxIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzg1NTkxMjYxLCJleHAiOjE3ODU2Nzc2NjF9.TEdT0qGPcIjf9FS8nWuIHIRkgkzctnRNjHyVxP2E_Qb0SDLnIC3ODJvz1Z84Mv-T


###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "newuseer1",
  "password": "test1234"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "test1234"
}

###

DELETE http://localhost:8080/api/books/32
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJyb2xldGVzdDciLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc4NTY3MzUxOCwiZXhwIjoxNzg1NzU5OTE4fQ._3Zj4T-HmabJNXJkAIw4iXIwmb6joYV2EvGIHMK1Br7SIVaGWtw2oAzFjTmE6m7g

###
GET http://localhost:8080/api/books/search?title=harry
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg1ODUwNTQ2LCJleHAiOjE3ODU5MzY5NDZ9.IS39qa8gjDENiPG9Pvp3HpsngYMGh0iAVBV2g0y27pdGUfs_bZeHAGUKqmoBsVE1

###
GET /api/books/filter?title=harry

###
GET http://localhost:8080/api/books/filter?title=harry
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg2MTcyNTEzLCJleHAiOjE3ODYyNTg5MTN9.hhTloTiS-1Klt6OyMnyeNDyU1Ps8L_oIqDIXFbnahkc

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "test1234"
}
###
GET http://localhost:8080/api/books/filter?title=harry&year=1997
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg2MTcyNTEzLCJleHAiOjE3ODYyNTg5MTN9.hhTloTiS-1Klt6OyMnyeNDyU1Ps8L_oIqDIXFbnahkc