spring.application.name=library

spring.datasource.url=jdbc:postgresql://localhost:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=Saiq2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

